# task1

In [2]:
import numpy as np

In [3]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [4]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = np.array([a[:,0].mean(),a[:,1].mean()])

In [6]:
mean_a

array([2. , 8.4])

# task2

In [7]:
a_centered = a - mean_a

In [9]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# task3

In [12]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1] 

In [13]:
a_centered_sp

8.0

In [14]:
a_centered_sp/4

2.0

# task4

In [18]:
x = np.cov(a.T)

In [19]:
x

array([[1. , 2. ],
       [2. , 4.3]])

In [20]:
x[0,1]

2.0