# Задание 5 (повторение материала)

In [1]:
import numpy as np

In [2]:
a = np.arange(12,24)
x = len(a)

In [3]:
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [4]:
x

12

In [5]:
for i in [2,3,4,6,12]:
    b = np.reshape(a, (i, int(x / i)))
    print(b)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [6]:
for i in [2,3,4,6,12]:
    c = np.reshape(a, (i, -1))
    print(c)

[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


### Массив numpy из 1 столбца и 12 строк можно назвать одномерным

In [7]:
c.shape

(12, 1)

In [8]:
d = np.random.randn(3, 4)
d

array([[-0.88122921,  0.9876429 ,  1.16972498,  0.45530165],
       [-0.04133655, -0.37470716,  0.27934392,  0.68022011],
       [-0.72663763, -2.01898944,  1.95902715,  1.01049157]])

In [9]:
e = d.flatten()
e

array([-0.88122921,  0.9876429 ,  1.16972498,  0.45530165, -0.04133655,
       -0.37470716,  0.27934392,  0.68022011, -0.72663763, -2.01898944,
        1.95902715,  1.01049157])

In [10]:
a = np.arange(20, 0, -2)
print(a)
a.shape

[20 18 16 14 12 10  8  6  4  2]


(10,)

In [11]:
b = np.zeros((1,10), dtype=int)
k = 0
for i in range(20, 0, -2):
    b[0][k] = i
    k += 1
print(b)
b.shape

[[20 18 16 14 12 10  8  6  4  2]]


(1, 10)

In [12]:
print(a.ndim)
print(b.ndim)

1
2


### У массивов a и b разные размерности

In [13]:
a = np.zeros((2,2))
a.size

4

In [14]:
b = np.ones((3,2))
b.size

6

In [15]:
c = np.vstack((a,b))
print(c.size)
print(c)

10
[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
b = np.reshape(a,(4,3))
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
At = b.transpose()
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [19]:
B = np.dot(b, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [20]:
B.size

16

In [21]:
np.linalg.det(B)

0.0

### Так как определитель матрицы B равен 0, то обратную матрицу найти невозможно.

In [22]:
np.random.seed(42)

In [23]:
c = np.random.randint(0,16,16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [24]:
C = np.reshape(c, (4,-1))
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [25]:
D = B + C*10
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [26]:
np.linalg.det(D)

-28511999.999999944

In [27]:
np.linalg.matrix_rank(D)

4

In [28]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [29]:
D_copy = D_inv > 0
D_inv = D_copy.astype(int)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [30]:
D_inv[(D_inv != 0) & (D_inv != 1)].size

0

In [31]:
print(B)
print(C)
E = np.where(D_inv, B, C)
print(E)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]
